/**
 * Generated by scripts/build_kitchen_bath_gallery.js - do not edit by hand.
 *
 * Real Profixter kitchen and bathroom photography, resized for the web from
 * the camera originals in `public/Bath And Kitchen`. Dimensions are the
 * generated file's own, so every tile can reserve its exact box before the
 * image arrives.
 */

export type GalleryCategory = "kitchens" | "bathrooms" | "showers" | "details";
export type GallerySpan = "feature" | "wide" | "tall" | "standard";

export type GalleryPhoto = {
  slug: string;
  src: string;
  width: number;
  height: number;
  alt: string;
  category: GalleryCategory;
  span: GallerySpan;
  hero: boolean;
  /**
   * Set where several frames are demonstrably the same room: consecutive
   * camera filenames and the same tile, vanity and floor across the photos.
   * Used only to keep them adjacent in the grid.
   */
  group: string | null;
  blurDataURL: string;
};

export const KITCHEN_BATH_PHOTOS: GalleryPhoto[] = [
  {
    "slug": "bath-shiplap-skylight",
    "src": "/images/kitchen-bath/bath-shiplap-skylight.webp",
    "width": 2600,
    "height": 1950,
    "alt": "Renovated bathroom with a freestanding tub, a tiled walk-in shower with a built-in bench, white shiplap walls and a skylight above.",
    "category": "bathrooms",
    "span": "feature",
    "hero": true,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoMAAkAA4BaJZwAAuU/ts8wAPyPWcm4KdGl5nDlFIXyvQ156fZWj+aBFE7jhoVcYssXVXRwAAA="
  },
  {
    "slug": "kitchen-navy-island",
    "src": "/images/kitchen-bath/kitchen-navy-island.webp",
    "width": 828,
    "height": 828,
    "alt": "Renovated kitchen with white shaker cabinets, a navy island with a marble-look countertop, brick-pattern backsplash and glass pendant lights.",
    "category": "kitchens",
    "span": "standard",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoMAAwAA4BaJYwC7AD7JHwfcEAA/rWtVRa5UMGa4QKvY/4/CueeMJbIE3Riiry168bRTkb+FF8LvLmZ7RyqeQAA"
  },
  {
    "slug": "bath-freestanding-tub-hex",
    "src": "/images/kitchen-bath/bath-freestanding-tub-hex.webp",
    "width": 720,
    "height": 899,
    "alt": "Renovated bathroom with a freestanding oval tub, marble-look wall tile, a white vanity and dark hexagon floor tile.",
    "category": "bathrooms",
    "span": "standard",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAQCdASoMAA8AA4BaJZQAAuWoSaAAAP6x5riCmbFHVTh4Xq1F0x3+sJfIDo6mCNWIZKXbGjutsvhPvywOth/DufbjoEAA"
  },
  {
    "slug": "shower-marble-gold-tub",
    "src": "/images/kitchen-bath/shower-marble-gold-tub.webp",
    "width": 828,
    "height": 828,
    "alt": "Tub and shower lined in marble-look tile with a decorative diamond tile band, brass fixtures and a sliding glass door.",
    "category": "showers",
    "span": "standard",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoMAAwAA4BaJYwC7AEWY1bgAAD+WtIjLjw5nKK52p5lDg2z+2bQQBKbM6F4MAAA"
  },
  {
    "slug": "bath-round-mirror-vanity",
    "src": "/images/kitchen-bath/bath-round-mirror-vanity.webp",
    "width": 828,
    "height": 828,
    "alt": "Renovated bathroom with a white vanity, marble-look countertop, a round backlit mirror and a geometric patterned feature wall.",
    "category": "bathrooms",
    "span": "standard",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACQAQCdASoMAAwAA4BaJZQAAas8iKAA/pGmEGeJ8fjdK2QvVnAswcYDxAx0vGqOXb9TYJoak4jU975+jut20MAA"
  },
  {
    "slug": "kitchen-handleless-island",
    "src": "/images/kitchen-bath/kitchen-handleless-island.webp",
    "width": 2000,
    "height": 1500,
    "alt": "Modern kitchen renovation with handleless cabinets, a large island with a white countertop, herringbone tile backsplash and a built-in cooktop.",
    "category": "kitchens",
    "span": "wide",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoMAAkAA4BaJZwAAxZeOKecMADiRayTimxWC0P2J5Xk2pVXVdN24OKq3F6AHuAAAAA="
  },
  {
    "slug": "shower-marble-glass-hex",
    "src": "/images/kitchen-bath/shower-marble-glass-hex.webp",
    "width": 828,
    "height": 1034,
    "alt": "Walk-in shower with large marble-look wall tile, a frameless glass enclosure and hexagon mosaic floor tile.",
    "category": "showers",
    "span": "standard",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoMAA8AA4BaJYwCdAC95oiGugAAzW5HR7HSJ/TmMfm+vW3nqN7h81xs6P27uMm/YHTNL6EkfaNOnz3AXtLJaPYAAAA="
  },
  {
    "slug": "shower-mosaic-niche-glass",
    "src": "/images/kitchen-bath/shower-mosaic-niche-glass.webp",
    "width": 828,
    "height": 1035,
    "alt": "Walk-in shower with marble-look wall tile, two mosaic-lined niches and a frameless glass enclosure.",
    "category": "showers",
    "span": "standard",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoMAA8AA4BaJZQC7AD0oLTK3oAAziLsX9c50GBmQV4+cPSe9D1gZNYgIaSDQr8kGmH1wV4Iu8WZs6Y3jy97YmXDgAA="
  },
  {
    "slug": "bath-dark-marble-suite",
    "src": "/images/kitchen-bath/bath-dark-marble-suite.webp",
    "width": 1744,
    "height": 2000,
    "alt": "Large renovated primary bathroom with dark marble-look wall panels, a freestanding tub, a navy double vanity and a glass shower enclosure.",
    "category": "bathrooms",
    "span": "feature",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoMAA4AA4BaJZQCw7DcpPD0OcMAAPk8iwbsnf4b3WKa1J6NRT1ldfz1U5ug9omfRGpztpOebyzi5Dhi7E9SV4cWZCgZdz2pSAAAAA=="
  },
  {
    "slug": "shower-striated-stone",
    "src": "/images/kitchen-bath/shower-striated-stone.webp",
    "width": 1500,
    "height": 2000,
    "alt": "Walk-in shower lined in grey striated stone-look tile with a pebble floor and a glass panel.",
    "category": "showers",
    "span": "tall",
    "hero": false,
    "group": "striated-stone",
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAQCdASoMABAAA4BaJQBOgBwfPa4AAM3OlqFJgDaCtlmByMUaBVZOVjR4wGKa0iWEfkAXEawEEheT0pG9ZZRVl7Rd+pQ7y/nPflRmQP6m8AAA"
  },
  {
    "slug": "detail-striated-tile-window",
    "src": "/images/kitchen-bath/detail-striated-tile-window.webp",
    "width": 1500,
    "height": 2000,
    "alt": "Close view of grey striated stone-look tile running across a shower wall and around a window opening.",
    "category": "details",
    "span": "tall",
    "hero": false,
    "group": "striated-stone",
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAQCdASoMABAAA4BaJYgCdABf1yAAAPwe8Wr8Yddq8oSkMS2AK4CHiw7v/Jw5/kI16C5xK0IuTWaRLIi+vHyQE+xRNGQWoYIDESMhwAA="
  },
  {
    "slug": "bath-backlit-vanity-stone",
    "src": "/images/kitchen-bath/bath-backlit-vanity-stone.webp",
    "width": 2000,
    "height": 1500,
    "alt": "Renovated bathroom with a white floating double vanity, a large backlit mirror and a glass shower lined in grey striated stone-look tile.",
    "category": "bathrooms",
    "span": "wide",
    "hero": false,
    "group": "striated-stone",
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoMAAkAA4BaJZQAAlqXOXRMAAD9utdd8Ix82HaCRBjQ5McVC/I+vD0fjKevdb+oAT2jF+32T9toDuktLX9hYS2lIAA="
  },
  {
    "slug": "kitchen-grey-shaker-island",
    "src": "/images/kitchen-bath/kitchen-grey-shaker-island.webp",
    "width": 1080,
    "height": 1080,
    "alt": "Renovated kitchen with grey shaker cabinets, a granite-look island, stainless steel range hood and marble-look tile flooring.",
    "category": "kitchens",
    "span": "standard",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQAgCdASoMAAwAA4BaJZQC7AD0uPnqylxAANvAY1LDfsAOXDKOud5dBh2dLUq1/bghIQlGSbzK7fAQFzQWOyN/Ff1UHtAAAAA="
  },
  {
    "slug": "bath-marble-tub-hex",
    "src": "/images/kitchen-bath/bath-marble-tub-hex.webp",
    "width": 828,
    "height": 1034,
    "alt": "Renovated bathroom with marble-look wall tile, a freestanding tub, a glass shower panel and dark hexagon floor tile.",
    "category": "bathrooms",
    "span": "standard",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoMAA8AA4BaJYwAApLLTdNqvYAA/mlNiwMtvgh9IZOb+3bTG+nzLqiYdTxf0M5d47m4nmfX7934IrFswj1c2WSZNv3CygAA"
  },
  {
    "slug": "shower-black-marble-glass",
    "src": "/images/kitchen-bath/shower-black-marble-glass.webp",
    "width": 1440,
    "height": 1440,
    "alt": "Shower with white and black marble-look tile, a glass enclosure, a wall niche and a built-in tub surround.",
    "category": "showers",
    "span": "wide",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoMAAwAA4BaJZQCdADbpXLKjFAA/pOZ8YVPxu4nTPLHBJvI2T4fo1rcxAADzYiDzihEXgwMumN6oVmyo177uwt/ubbLL+UbEw5r5QAA"
  },
  {
    "slug": "shower-hex-black-fixtures",
    "src": "/images/kitchen-bath/shower-hex-black-fixtures.webp",
    "width": 828,
    "height": 1034,
    "alt": "Walk-in shower with white hexagon mosaic wall tile, a built-in niche, a stone bench and matte black fixtures.",
    "category": "showers",
    "span": "standard",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACQAQCdASoMAA8AA4BaJZQAAbdcxAAA/mFbMyfpNkl6Hf0DfPvV3+BQr1RByisRFn22oSL3tI/FnEf5OgsyAwHkt9d5a0/G875lq1X+emeAAA=="
  },
  {
    "slug": "bath-slab-marble-vanity",
    "src": "/images/kitchen-bath/bath-slab-marble-vanity.webp",
    "width": 828,
    "height": 1034,
    "alt": "Renovated bathroom with large marble-look wall slabs, a backlit mirror, a grey vanity and a glass shower.",
    "category": "bathrooms",
    "span": "standard",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQAgCdASoMAA8AA4BaJYwCdAC2TlHzaF4AAPfYG4B2HSwmvYhzU8b4G4HgTLRgwZrKR/+AuQe5/bitChVV9BCjBEaOUAAA"
  },
  {
    "slug": "shower-decorative-niche-gold",
    "src": "/images/kitchen-bath/shower-decorative-niche-gold.webp",
    "width": 1500,
    "height": 2000,
    "alt": "Walk-in shower with white wall tile, a tall decorative tile niche, brass fixtures and patterned floor tile.",
    "category": "showers",
    "span": "tall",
    "hero": false,
    "group": "gold-patterned",
    "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoMABAAA4BaJQBOgCHhJ2RUAAAA4nnW7Mb3srmnAf5KmmXreit2C5vaZVFlbHcWMvJQ4gqj6BRsaAAA"
  },
  {
    "slug": "shower-gold-window-patterned",
    "src": "/images/kitchen-bath/shower-gold-window-patterned.webp",
    "width": 1500,
    "height": 2000,
    "alt": "Walk-in shower with white wall tile, a brass rain head and hand shower, a window and patterned floor tile.",
    "category": "showers",
    "span": "standard",
    "hero": false,
    "group": "gold-patterned",
    "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoMABAAA4BaJYwAAlyol5/rgAD+XlJuFGSAWGj4QO+7WQ/b2YzeqdYyGu0uZS4tgHmV4WeUVgAAAA=="
  },
  {
    "slug": "bath-navy-vanity-shiplap",
    "src": "/images/kitchen-bath/bath-navy-vanity-shiplap.webp",
    "width": 1500,
    "height": 2000,
    "alt": "Renovated bathroom with a navy vanity, white shiplap walls, a black-framed mirror and patterned floor tile.",
    "category": "bathrooms",
    "span": "tall",
    "hero": false,
    "group": "gold-patterned",
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAQCdASoMABAAA4BaJQAAS7cJcEDN6AD+07d/UjHlldd2wQv0+Ut7vT5WawGbC5m18Pm2pJWXxrvvKaQdZmW8qdfwvY6I4tDjEAYYXvIh26raasGVi+b6AAA="
  },
  {
    "slug": "kitchen-wine-wall",
    "src": "/images/kitchen-bath/kitchen-wine-wall.webp",
    "width": 2000,
    "height": 1535,
    "alt": "Open kitchen renovation with white cabinets, a built-in wine rack column, a range hood and an island with upholstered bar stools.",
    "category": "kitchens",
    "span": "feature",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoMAAkAA4BaJQBWACLKGJultwAA/ohNstZ/sJwm050VusQPXvshoS0I2JonTW2s0G0QT0YtQ54Jyb3ftYAJXGoAAAA="
  },
  {
    "slug": "bath-double-vanity-gold",
    "src": "/images/kitchen-bath/bath-double-vanity-gold.webp",
    "width": 828,
    "height": 828,
    "alt": "Renovated bathroom with a white double vanity, a wide mirror, brass wall sconces and a glass shower enclosure.",
    "category": "bathrooms",
    "span": "standard",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoMAAwAA4BaJQBWAB6KE+ITQMAA/kC0/GKmX7Dyea3zE/8sEMMo6clRPyTn9nc6Cn0o6+pF7AIB2LZYpBeSzjnIvSWayh2jDiAAAA=="
  },
  {
    "slug": "bath-double-vanity-brass-mirror",
    "src": "/images/kitchen-bath/bath-double-vanity-brass-mirror.webp",
    "width": 828,
    "height": 828,
    "alt": "Renovated bathroom with a white double vanity, a brass-framed mirror and brass wall sconces.",
    "category": "bathrooms",
    "span": "standard",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoMAAwAA4BaJQBOgBpCYT9mjgAA4c8nBVdb7pKnIXEVFFGiDAxqw3GKqe/GW6qKSZZOLnJvZaBX1p0Dh4poTNBpnm73Qu9AAAA="
  },
  {
    "slug": "bath-wood-vanity-marble",
    "src": "/images/kitchen-bath/bath-wood-vanity-marble.webp",
    "width": 1500,
    "height": 2000,
    "alt": "Renovated bathroom with a wood floating double vanity, marble-look wall tile, a wood-panel accent wall and a built-in tub.",
    "category": "bathrooms",
    "span": "tall",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADwAQCdASoMABAAA4BaJYwCdADbPi7B+jAA/tYRFdhqxmcXB3WndRSImBdo/Dz3G/P/Q/H+v5fQm4WjRE1TnE1AEgMzkgC9OcmXbndmwg4Pt0cyta4Hl4ri9yPIq2d8oAA="
  },
  {
    "slug": "shower-marble-black-fixtures",
    "src": "/images/kitchen-bath/shower-marble-black-fixtures.webp",
    "width": 828,
    "height": 1034,
    "alt": "Walk-in shower with marble-look wall tile, a rain shower head, matte black fixtures and hexagon mosaic tile.",
    "category": "showers",
    "span": "standard",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACwAQCdASoMAA8AA4BaJZQAAtxqU2OAAP7oZC7uv1Mvbdr0rl/2LiKaV8FO48sxTHnU7xI5KcbkUtIm9t+re5h6GygPTNKdVKiOgljEQz4tb2nVnTeLgAAA"
  },
  {
    "slug": "shower-glass-vanity-black",
    "src": "/images/kitchen-bath/shower-glass-vanity-black.webp",
    "width": 828,
    "height": 1034,
    "alt": "Walk-in shower with a black-framed glass enclosure beside a white vanity with a backlit mirror and black fixtures.",
    "category": "showers",
    "span": "standard",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoMAA8AA4BaJZQAAlrK9EIW8AD+ZYWnTmD9dOqa5PvA6UtGKeCQKWqsflJ1vMv7xQA7uQ3cHtwS/1GYKJwYccvjfT+mhEyH373sBwAA"
  },
  {
    "slug": "kitchen-cream-shaker",
    "src": "/images/kitchen-bath/kitchen-cream-shaker.webp",
    "width": 1080,
    "height": 1080,
    "alt": "Renovated kitchen with cream shaker cabinets, stainless steel appliances, a built-in wine rack and wood-look tile flooring.",
    "category": "kitchens",
    "span": "standard",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQAgCdASoMAAwAA4BaJQBOgCLXQGhjVlgAAOJ5xqkXFbRts5XuroUuLbLgKxgwihx8GB0cjFOLWDiW8kzk7XXKA1RrlUAA"
  },
  {
    "slug": "shower-stacked-stone-warmer",
    "src": "/images/kitchen-bath/shower-stacked-stone-warmer.webp",
    "width": 1500,
    "height": 2000,
    "alt": "Walk-in shower with a stacked stone accent wall, large-format tile and a wall-mounted towel warmer.",
    "category": "showers",
    "span": "tall",
    "hero": false,
    "group": "stacked-stone",
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoMABAAA4BaJYwCdAD8KTIEwGAAAP3jEm7i2QSfPYwU4BYpMkoASX8nUMebmFX3aD88vD+K7Ar4uG4i67VqEHqfQZDIurGgAAA="
  },
  {
    "slug": "detail-stacked-stone",
    "src": "/images/kitchen-bath/detail-stacked-stone.webp",
    "width": 1500,
    "height": 2000,
    "alt": "Close view of a stacked stone accent wall meeting large-format tile inside a shower.",
    "category": "details",
    "span": "standard",
    "hero": false,
    "group": "stacked-stone",
    "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoMABAAA4BaJYwCdADa6LskIAAA4nu83pNdYv+X1MUM6j0T0UKfbA/Wad8Qo5+uwQOBeEWceqzk/Rz1gAA="
  },
  {
    "slug": "shower-grey-bench",
    "src": "/images/kitchen-bath/shower-grey-bench.webp",
    "width": 1500,
    "height": 2000,
    "alt": "Walk-in shower with large-format grey wall tile, a built-in bench, a wall niche and a rain shower head.",
    "category": "showers",
    "span": "tall",
    "hero": false,
    "group": "grey-large-format",
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoMABAAA4BaJaQAArJMwUZr/gAA/I27lXAzIAgEEQ05MnPMSZmx/ILKyFHmAnOOlqJuNzRK2hMl7A8LZaHw/DL4DgAAAA=="
  },
  {
    "slug": "shower-grey-glass-vanity",
    "src": "/images/kitchen-bath/shower-grey-glass-vanity.webp",
    "width": 2000,
    "height": 1500,
    "alt": "Walk-in shower with large-format grey tile and a glass panel, next to a white vanity.",
    "category": "showers",
    "span": "wide",
    "hero": false,
    "group": "grey-large-format",
    "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoMAAkAA4BaJZwAApxrZVR2AAD+mPg9xsEyu6QPWdnJ/KjGqNFvCk2+seUp26qJ6tCb1KBAAAA="
  },
  {
    "slug": "bath-grey-double-vanity",
    "src": "/images/kitchen-bath/bath-grey-double-vanity.webp",
    "width": 1500,
    "height": 2000,
    "alt": "Renovated bathroom with a white double vanity, two mirrors, wall sconces and large-format grey wall tile.",
    "category": "bathrooms",
    "span": "standard",
    "hero": false,
    "group": "grey-large-format",
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoMABAAA4BaJQBOgBoTiJblKAAA/l9fZYmieCBMYRIMq6lPKBa4px1BU+Cjav0H1y/q345CtG4UpU+aik4sF6uXN9OW/9gAAAA="
  },
  {
    "slug": "kitchen-white-peninsula",
    "src": "/images/kitchen-bath/kitchen-white-peninsula.webp",
    "width": 1080,
    "height": 1350,
    "alt": "Renovated kitchen with white cabinets, a raised breakfast peninsula with bar stools and glass pendant lighting.",
    "category": "kitchens",
    "span": "standard",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACQAgCdASoMAA8AA4BaJYwCdAYtVUmyuIqjdd20gAD0XoyJdhIXl0zyHDr5yjT/WWncLDLwzzBA3ladHVBEGQngmM7VvOBixS4tsgsAUk5kCL9qQ8oahONAxlayn4vAAAA="
  },
  {
    "slug": "shower-fishscale-mosaic",
    "src": "/images/kitchen-bath/shower-fishscale-mosaic.webp",
    "width": 1500,
    "height": 2000,
    "alt": "Walk-in shower with blue fish-scale mosaic wall tile, a black tile border and a speckled terrazzo-look floor.",
    "category": "showers",
    "span": "standard",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoMABAAA4BaJYwCdAELYEMs0umAAP6myH6FCcNWx4+z7Dc2QDt0QGh8mECBSt8iIrc5BhNERrKrnY2NOTaTImaoqqFQKSiGP7ywAA=="
  },
  {
    "slug": "shower-wood-look-niches",
    "src": "/images/kitchen-bath/shower-wood-look-niches.webp",
    "width": 1500,
    "height": 2000,
    "alt": "Tub and shower surround in wood-look tile with a column of stacked built-in niches.",
    "category": "showers",
    "span": "tall",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAABwAgCdASoMABAAA4BaJQBOgMXX4FmbUoF7NgMAAP5+o/maQ07N/E2jXeaiX7jyllzQkpDBZWa8GvKv4TS1IW1fGGAizEX4P4xPbEm2wuicMqGi9UCZ8gAA"
  },
  {
    "slug": "shower-tub-niche-band",
    "src": "/images/kitchen-bath/shower-tub-niche-band.webp",
    "width": 1500,
    "height": 2000,
    "alt": "Tub and shower surround in marble-look tile with a decorative patterned niche and a wall-mounted shower fitting.",
    "category": "showers",
    "span": "standard",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAwAgCdASoMABAAA4BaJYwCdAD1csoaXbKfgAD31GysApwVmhiLi4Jry+m2JvZXvkKWg1UvgRfeOynuKr8ZDwdpGv8ynXd+AAA="
  },
  {
    "slug": "detail-tub-tile-niche",
    "src": "/images/kitchen-bath/detail-tub-tile-niche.webp",
    "width": 1500,
    "height": 2000,
    "alt": "Tub surround in marble-look tile with a long decorative patterned niche above it.",
    "category": "details",
    "span": "standard",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoMABAAA4BaJYwCdADC+Ui1XV8AAP6a/GotpTEwSzd1FEApId/k1zjs7zlc9aIFSaLCZXqZA1F/qEFl7l5FS0hPcW1iOIPjrZ4GBq4AAAA="
  },
  {
    "slug": "bath-vanity-marble-wood-mirror",
    "src": "/images/kitchen-bath/bath-vanity-marble-wood-mirror.webp",
    "width": 1080,
    "height": 1350,
    "alt": "Renovated bathroom with a white vanity, marble-look wall tile and a wood-framed mirror.",
    "category": "bathrooms",
    "span": "standard",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoMAA8AA4BaJZQCdADJmmtURwAA9odgqqy/FXn8bU9vQ1OIOxACWIIYMIjnHP6ypyt7NTdygb+hOfE0gqGtAnLh0ph+WRdnCqAAAA=="
  },
  {
    "slug": "bath-grey-vanity-pebble-floor",
    "src": "/images/kitchen-bath/bath-grey-vanity-pebble-floor.webp",
    "width": 1500,
    "height": 2000,
    "alt": "Renovated bathroom with a grey double vanity, a wide mirror, grey wall tile and pebble-pattern floor tile.",
    "category": "bathrooms",
    "span": "standard",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACwAQCdASoMABAAA4BaJZwAAxUm4KfgAP3juTjqA71CfrZ94ZPN8V3lvfmPKH+EwuAhwhQws1NcONo7OBAAAA=="
  },
  {
    "slug": "bath-glass-shower-hex-floor",
    "src": "/images/kitchen-bath/bath-glass-shower-hex-floor.webp",
    "width": 828,
    "height": 1034,
    "alt": "Renovated bathroom with a glass shower enclosure, marble-look wall tile and hexagon floor tile.",
    "category": "bathrooms",
    "span": "standard",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoMAA8AA4BaJZwAAutLa459P0oAAP6ZGKha137jQrwVdUJ717BYncmzW587NBYCFGHRuRwmVvwde5uNal0cMKmbTz/3eLgA"
  },
  {
    "slug": "detail-arabesque-backsplash",
    "src": "/images/kitchen-bath/detail-arabesque-backsplash.webp",
    "width": 2000,
    "height": 1866,
    "alt": "Kitchen wall with white shaker cabinets, a dark chevron range hood and a blue arabesque tile backsplash.",
    "category": "details",
    "span": "wide",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACQAQCdASoMAAsAA4BaJZQAAlk+ixoA/peazKga8dxm70JpxUU+urBQwNhG0GD4q5FMEgssdTBfO9lVBtZpQyoh4r70swAA"
  },
  {
    "slug": "detail-marble-mosaic-tub-deck",
    "src": "/images/kitchen-bath/detail-marble-mosaic-tub-deck.webp",
    "width": 2000,
    "height": 1260,
    "alt": "Bathroom under construction with marble mosaic tile on the walls and a tiled tub deck beneath a window.",
    "category": "details",
    "span": "wide",
    "hero": false,
    "group": null,
    "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoMAAgAA4BaJZwAAv13iQSC2jgA/gX4WVyGTZfmMODLNJ2k5t5UkDcerJtXQXd5uawvlSJyRF+LJA4A"
  }
];

export const KITCHEN_BATH_HERO =
  KITCHEN_BATH_PHOTOS.find((photo) => photo.hero) ?? KITCHEN_BATH_PHOTOS[0];

export function photosByCategory(category: GalleryCategory): GalleryPhoto[] {
  return KITCHEN_BATH_PHOTOS.filter((photo) => photo.category === category);
}

export function photoBySlug(slug: string): GalleryPhoto | undefined {
  return KITCHEN_BATH_PHOTOS.find((photo) => photo.slug === slug);
}
