/*
 * Builds app/desktop-scale.css: the customer site's type and section spacing
 * from 640px up, made fluid.
 *
 *   node scripts/build_desktop_scale.js          write the file
 *   node scripts/build_desktop_scale.js --check  fail if it is stale
 *
 * `npm run build` and `npm run dev` run this first, so a build (local, Vercel
 * preview or production) always ships CSS made from the source it is building.
 * The file is still committed, so a plain `next build` works too; --check
 * (in scripts/test_desktop_scale.js) catches a commit that forgot to refresh it.
 *
 * Why it is generated: big headings are written as Tailwind utilities with
 * breakpoint jumps (text-[30px] sm:text-[46px] lg:text-[54px]). Each one is a
 * fixed size from its breakpoint up, so a 1024px laptop, a 1366x657 screen at
 * 150% zoom and a 2560px monitor all get the same 54px headline. Rather than
 * re-edit hundreds of components, this script finds every large size the code
 * uses and gives it one formula:
 *
 *   size(S) = clamp(floor, min(width term, height term), S)
 *
 *   floor        max(70% of S, 28px)   never smaller than a phone title
 *   width term   floor at 640px wide, rising linearly to S at 1440px
 *   height term  S at 800px tall, 90% at 657px, 75% at 430px (only S >= 40)
 *
 * S is the size the code asks for, so 1440px and up look exactly as designed.
 * Tailwind v4 puts utilities in a cascade layer and unlayered rules win, so
 * the rules below override the utilities without touching the components.
 * Breakpoint variants are emitted in Tailwind's own order inside their own
 * min-width queries, so the cascade picks the same class Tailwind would.
 *
 * Phones (< 640px) are app/mobile-scale.css. Everything is scoped to
 * html[data-surface="site"] (lib/surface.ts): the admin and the /event kiosk
 * are never touched.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const OUT = path.join(ROOT, "app", "desktop-scale.css");
const SCAN = ["app", "lib"];
// Staff surfaces never get the site scale, so their classes are not scanned.
const SKIP = [path.join("app", "admin"), path.join("app", "event")];

const BREAKPOINTS = [["", 640], ["sm", 640], ["md", 768], ["lg", 1024], ["xl", 1280], ["2xl", 1536]];
const NAMED = { "3xl": 30, "4xl": 36, "5xl": 48, "6xl": 60, "7xl": 72, "8xl": 96, "9xl": 128 };
const MIN_TYPE = 30;
// Shared CSS classes with a large size of their own (app/globals.css,
// app/free-visit.css), at the size each one is designed to reach. Their own
// clamp()s were tuned on a phone and hit the maximum by ~700px wide.
const SHARED = [
  [".lx-h1", 64],
  [".lx-h2", 48],
  [".mk-h2", 52],
  [".plan-box__figure", 64],
];
// Section bottom padding at or above this is scaled down on short screens.
// Top padding is left alone: on hero sections it clears the fixed header.
const MIN_PAD = 64;
const SPACING = 4; // Tailwind v4 --spacing, px

const r1 = (n) => Math.round(n * 100) / 100;

function fluidType(s) {
  const floor = Math.round(Math.max(0.7 * s, Math.min(s, 28)));
  if (floor >= s) return null;
  const width = `calc(${floor}px + (100vw - 640px) * ${Math.round(((s - floor) / 800) * 10000) / 10000})`;
  const height = `calc(${r1(0.45 * s)}px + ${r1((0.55 * s) / 8)}vh)`;
  const middle = s >= 40 ? `min(${width}, ${height})` : width;
  return `clamp(${floor}px, ${middle}, ${s}px)`;
}

function fluidPad(px) {
  return `clamp(${Math.round(px * 0.6)}px, ${r1((px / 900) * 100)}vh, ${px}px)`;
}

const escape = (cls) => cls.replace(/[:[\].]/g, (c) => `\\${c}`);

function walk(dir, files = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (SKIP.some((s) => path.relative(ROOT, p).startsWith(s))) continue;
    if (e.isDirectory()) walk(p, files);
    else if (/\.(tsx|ts|jsx|js)$/.test(e.name)) files.push(p);
  }
  return files;
}

function collect() {
  const type = new Map();
  const pad = new Map();
  const typeRe = /(?<![\w:-])(?:(sm|md|lg|xl|2xl):)?text-(?:\[(\d+(?:\.\d+)?)px\]|([3-9]xl))(?![\w-])/g;
  const padRe = /(?<![\w:-])(?:(sm|md|lg|xl|2xl):)?(py|pb)-(\d+)(?![\w.-])/g;
  for (const f of SCAN.flatMap((d) => walk(path.join(ROOT, d)))) {
    const src = fs.readFileSync(f, "utf8");
    for (const m of src.matchAll(typeRe)) {
      const size = m[2] ? Number(m[2]) : NAMED[m[3]];
      if (size >= MIN_TYPE) type.set(m[0], { bp: m[1] || "", size });
    }
    for (const m of src.matchAll(padRe)) {
      const px = Number(m[3]) * SPACING;
      if (px >= MIN_PAD) pad.set(m[0], { bp: m[1] || "", prop: m[2], px });
    }
  }
  return { type, pad };
}

function build() {
  const { type, pad } = collect();
  const lines = [
    "/* GENERATED by scripts/build_desktop_scale.js. Do not edit by hand. */",
    "/* The why and the formula are documented in that script. */",
    "",
  ];
  const sel = (cls) => `:root[data-surface="site"] .${escape(cls)}`;
  for (const [bp, min] of BREAKPOINTS) {
    const rules = bp ? [] : SHARED.map(([cls, size]) => `  :root[data-surface="site"] ${cls} { font-size: ${fluidType(size)}; }`);
    for (const [cls, v] of [...type].filter(([, v]) => v.bp === bp).sort((a, b) => a[1].size - b[1].size || (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0))) {
      const value = fluidType(v.size);
      if (value) rules.push(`  ${sel(cls)} { font-size: ${value}; }`);
    }
    for (const [cls, v] of [...pad].filter(([, v]) => v.bp === bp).sort((a, b) => a[1].px - b[1].px || (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0))) {
      const value = fluidPad(v.px);
      rules.push(`  ${sel(cls)} { padding-bottom: ${value}; }`);
    }
    if (!rules.length) continue;
    lines.push(`/* ${bp ? `${bp}: and up` : "unprefixed, from 640px"} */`, `@media (min-width: ${min}px) {`, ...rules, "}", "");
  }
  return lines.join("\n");
}

const css = build();
if (process.argv.includes("--check")) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8").replace(/\r\n/g, "\n") : "";
  if (current !== css) {
    console.error("app/desktop-scale.css is stale. Run: node scripts/build_desktop_scale.js");
    process.exit(1);
  }
  console.log("app/desktop-scale.css is up to date");
} else {
  fs.writeFileSync(OUT, css);
  console.log(`wrote ${path.relative(ROOT, OUT)} (${css.split("\n").length} lines)`);
}

module.exports = { fluidType, fluidPad };
